language: c
compiler: gcc
sudo: true
before install:
  - pip install cpp-coveralls
script: sudo python build.py

jobs:
  - stage: coverage
    after_success:
      - coveralls --exclude tests/ --exclude doc/ --gcov-options '\-lp'
